services:
  build:
    build:
      context: .
      target: builder
    volumes:
      - ./out:/app/out
    command: npm run build

  serve:
    build:
      context: .
      target: serve
    ports:
      - "${HOST_PORT:-4827}:80"
