#!/usr/bin/env bash
# Load / save deploy.config and gather connection settings interactively.

DEPLOY_CONFIG_FILE="${DEPLOY_ROOT}/deploy.config"

# Defaults (overridden by deploy.config / prompts) — Digital Wilderness on shared droplet
DEPLOY_HOST="${DEPLOY_HOST:-104.248.224.133}"
DEPLOY_USER="${DEPLOY_USER:-root}"
DEPLOY_SSH_KEY="${DEPLOY_SSH_KEY:-$HOME/.ssh/id_ed25519}"
DEPLOY_SSH_ALIAS="${DEPLOY_SSH_ALIAS:-wilderness-deploy}"
DEPLOY_REMOTE_DIR="${DEPLOY_REMOTE_DIR:-/opt/digital-wilderness}"
DEPLOY_APP_SUBDIR="${DEPLOY_APP_SUBDIR:-frontend}"
DEPLOY_DOMAIN="${DEPLOY_DOMAIN:-wilderness.oduor-arnold.com}"
DEPLOY_APP_PORT="${DEPLOY_APP_PORT:-7291}"
DEPLOY_GIT_URL="${DEPLOY_GIT_URL:-https://github.com/arnoldchrisoduor1/digitalwilderness.git}"
DEPLOY_BRANCH="${DEPLOY_BRANCH:-main}"
DEPLOY_SITE_NAME="${DEPLOY_SITE_NAME:-digital-wilderness}"
DEPLOY_COMPOSE_PROJECT="${DEPLOY_COMPOSE_PROJECT:-digital-wilderness}"
DEPLOY_NGINX_SITE="${DEPLOY_NGINX_SITE:-digital-wilderness}"
DEPLOY_INCLUDE_WWW="${DEPLOY_INCLUDE_WWW:-0}"
DEPLOY_PUBLIC_URL="${DEPLOY_PUBLIC_URL:-}"
# Cheap insurance: after our deploy, confirm the co-hosted portfolio is still up
DEPLOY_NEIGHBOR_URL="${DEPLOY_NEIGHBOR_URL:-https://oduor-arnold.com}"

# Absolute paths derived from config
deploy_local_app_dir() {
  echo "${DEPLOY_ROOT}/${DEPLOY_APP_SUBDIR}"
}

deploy_remote_compose_dir() {
  echo "${DEPLOY_REMOTE_DIR}/${DEPLOY_APP_SUBDIR}"
}

# Refuse values that would collide with the co-hosted portfolio site.
config_assert_isolation() {
  local problems=0
  if [[ "${DEPLOY_REMOTE_DIR}" == "/opt/portfolio_v3" ]]; then
    log_err "DEPLOY_REMOTE_DIR must not be /opt/portfolio_v3 (portfolio site)"
    problems=1
  fi
  if [[ "${DEPLOY_APP_PORT}" == "8472" ]]; then
    log_err "DEPLOY_APP_PORT must not be 8472 (portfolio site port)"
    problems=1
  fi
  if [[ "${DEPLOY_NGINX_SITE}" == "portfolio" ]]; then
    log_err "DEPLOY_NGINX_SITE must not be 'portfolio' (portfolio nginx site)"
    problems=1
  fi
  if [[ "${DEPLOY_COMPOSE_PROJECT}" == "portfolio_v3" ]]; then
    log_err "DEPLOY_COMPOSE_PROJECT must not be portfolio_v3"
    problems=1
  fi
  if [[ $problems -ne 0 ]]; then
    log_err "Aborting — fix deploy.config so Digital Wilderness stays isolated from the portfolio"
    return 1
  fi
  return 0
}

config_load() {
  if [[ -f "$DEPLOY_CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$DEPLOY_CONFIG_FILE"
  fi
  # Recompute public URL if still empty
  if [[ -z "${DEPLOY_PUBLIC_URL:-}" ]]; then
    if [[ -n "${DEPLOY_DOMAIN:-}" ]]; then
      DEPLOY_PUBLIC_URL="https://${DEPLOY_DOMAIN}"
    else
      DEPLOY_PUBLIC_URL="http://${DEPLOY_HOST}"
    fi
  fi
}

config_save() {
  cat >"$DEPLOY_CONFIG_FILE" <<EOF
# Generated by deploy.sh — local only (gitignored)
DEPLOY_HOST='${DEPLOY_HOST}'
DEPLOY_USER='${DEPLOY_USER}'
DEPLOY_SSH_KEY='${DEPLOY_SSH_KEY}'
DEPLOY_SSH_ALIAS='${DEPLOY_SSH_ALIAS}'
DEPLOY_REMOTE_DIR='${DEPLOY_REMOTE_DIR}'
DEPLOY_APP_SUBDIR='${DEPLOY_APP_SUBDIR}'
DEPLOY_DOMAIN='${DEPLOY_DOMAIN}'
DEPLOY_APP_PORT='${DEPLOY_APP_PORT}'
DEPLOY_GIT_URL='${DEPLOY_GIT_URL}'
DEPLOY_BRANCH='${DEPLOY_BRANCH}'
DEPLOY_SITE_NAME='${DEPLOY_SITE_NAME}'
DEPLOY_COMPOSE_PROJECT='${DEPLOY_COMPOSE_PROJECT}'
DEPLOY_NGINX_SITE='${DEPLOY_NGINX_SITE}'
DEPLOY_INCLUDE_WWW='${DEPLOY_INCLUDE_WWW}'
DEPLOY_PUBLIC_URL='${DEPLOY_PUBLIC_URL}'
DEPLOY_NEIGHBOR_URL='${DEPLOY_NEIGHBOR_URL}'
EOF
  change_record "[saved]     deploy.config → ${DEPLOY_HOST} (${DEPLOY_USER})"
  log_ok "Saved ${DEPLOY_CONFIG_FILE}"
}

# Interactive (or reuse-saved) config collection.
config_ensure() {
  config_load

  if [[ -f "$DEPLOY_CONFIG_FILE" ]]; then
    log_info "Found saved config: ${DEPLOY_USER}@${DEPLOY_HOST}  key=${DEPLOY_SSH_KEY}"
    log_info "App: ${DEPLOY_SITE_NAME}  dir=${DEPLOY_REMOTE_DIR}  port=${DEPLOY_APP_PORT}  nginx=${DEPLOY_NGINX_SITE}"
    if ui_confirm "Use saved server config?" Y; then
      config_load
      config_assert_isolation || return 1
      return 0
    fi
  fi

  ui_section "Server connection (Digital Wilderness — side-by-side with portfolio)"
  DEPLOY_HOST="$(ui_ask "Server host/IP" "$DEPLOY_HOST")"
  DEPLOY_USER="$(ui_ask "SSH user" "$DEPLOY_USER")"
  DEPLOY_SSH_KEY="$(ui_ask "SSH private key path" "$DEPLOY_SSH_KEY")"
  DEPLOY_SSH_ALIAS="$(ui_ask "SSH config alias" "$DEPLOY_SSH_ALIAS")"
  DEPLOY_REMOTE_DIR="$(ui_ask "Remote project directory" "$DEPLOY_REMOTE_DIR")"
  DEPLOY_APP_SUBDIR="$(ui_ask "App subdirectory (compose + build)" "$DEPLOY_APP_SUBDIR")"
  DEPLOY_DOMAIN="$(ui_ask "Domain (blank = use IP / skip SSL)" "${DEPLOY_DOMAIN}")"
  DEPLOY_APP_PORT="$(ui_ask "Container host port (portfolio uses 8472)" "$DEPLOY_APP_PORT")"
  DEPLOY_COMPOSE_PROJECT="$(ui_ask "Docker Compose project name" "$DEPLOY_COMPOSE_PROJECT")"
  DEPLOY_NGINX_SITE="$(ui_ask "Nginx site name (sites-available/…)" "$DEPLOY_NGINX_SITE")"
  DEPLOY_GIT_URL="$(ui_ask "Git clone URL" "$DEPLOY_GIT_URL")"
  DEPLOY_BRANCH="$(ui_ask "Git branch" "$DEPLOY_BRANCH")"
  DEPLOY_NEIGHBOR_URL="$(ui_ask "Neighbor site URL (post-deploy check)" "$DEPLOY_NEIGHBOR_URL")"

  if [[ -n "$DEPLOY_DOMAIN" ]]; then
    DEPLOY_PUBLIC_URL="https://${DEPLOY_DOMAIN}"
  else
    DEPLOY_PUBLIC_URL="http://${DEPLOY_HOST}"
  fi
  DEPLOY_PUBLIC_URL="$(ui_ask "Public URL for reachability checks" "$DEPLOY_PUBLIC_URL")"

  config_assert_isolation || return 1

  if ui_confirm "Save this config to deploy.config?" Y; then
    config_save
  fi
}
